"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import Auto from "@/public/assets/Rectangle 101.png";

import Chart1 from "@/public/assets/Chart 1.png";
import Chart2 from "@/public/assets/Chart 2.png";
import Chart3 from "@/public/assets/Chart 3.png";
import Image, { StaticImageData } from "next/image";

import { useState, useEffect, FC, MouseEventHandler } from "react";
import DropdownButton from "../../DropdownButton/DropdownButton";
import { LocationIcon } from "@/public/icons";

import { FaHeart } from "react-icons/fa6";

function convertDateWithSlashes(date: Date) {
  return `${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`;
}

function formatNumberWithCommas(number: number) {
  return number.toLocaleString("en-US");
}

interface iBusinessData {
  image: string | StaticImageData;
  name: string;
  description: string;
  interest: string;
  amount: number;
  location: string;
  liked: boolean;
  businessStatus: string;
  status: string;
}

const ACCEPTED = "Accepted",
  PROPOSED = "Proposed",
  REJECTED = "Rejected";

const BuyerOverview = () => {
  const [businesses, setBusinesses] = useState<iBusinessData[]>([]);
  const [sortFilter, setSortFilter] = useState<string | null>(null);
  const [filter, setFilter] = useState<string | null>(null);
  const [currentBusiness, setCurrentBusiness] = useState<number>(-1);

  useEffect(() => {
    setBusinesses([
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Business for sale",
        interest: "Agriculture Web",
        liked: true,
        status: PROPOSED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Investment required",
        interest: "Agriculture Web",
        liked: false,
        status: ACCEPTED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Loan required",
        interest: "Agriculture Web",
        liked: false,
        status: REJECTED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Business for sale",
        interest: "Agriculture Web",
        liked: true,
        status: PROPOSED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Investment required",
        interest: "Agriculture Web",
        liked: false,
        status: ACCEPTED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Loan required",
        interest: "Agriculture Web",
        liked: false,
        status: REJECTED,
      },
    ]);
  }, []);

  return (
    <>
      <div className="pt-4 overflow-y-scroll h-[90vh] md:h-auto px-[40px] md:px-5 pb-10">
        <h2 className="text-3xl md:text-[20px] md:leading-[30px] font-bold text-black md:mt-10 mt-2">
          Overview
        </h2>
        <div className="flex justify-between md:gap-6 md:justify-start mt-4 md:overflow-x-auto scrollbar-custom">
          <DashboardCard
            leading={"Total Balance"}
            content={"₦400,000"}
            trailing={`${convertDateWithSlashes(new Date())} last withdrawn`}
            chart={Chart1}
            tooltip={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
            className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          />
          <DashboardCard
            leading={"Total Sold Acquisitions"}
            content={"50"}
            trailing={"09 businesses"}
            chart={Chart2}
            tooltip={
              "This shows the total number of companies you have acquired."
            }
            className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          />
          <DashboardCard
            leading={"Total Proposed Businesses"}
            content={"32"}
            trailing={"09 businesses"}
            chart={Chart3}
            tooltip={"This shows your company's total years of operation."}
            className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          />
        </div>
        <div className="flex justify-between md:flex-col md:mb-10 w-full mt-6">
          <div className="bg-white rounded border-contrast-10 border-[1.5px] w-full shadow-sm">
            <div className="flex md:flex-col md:justify-center justify-between px-4 h-[74px] md:h-[122px] md:items-start items-center border-b-[1.5px] border-contrast-10">
              <h2 className="bold-1 md:text-[20px] md:leading-[30px] text-contrast-100">
                Acquired Businesses
              </h2>

              <div className="flex gap-3 md:mt-4">
                <DropdownButton
                  menus={[
                    {
                      name: "Business for Sale",
                      onClick: (e) => {
                        setSortFilter("Business for Sale");
                      },
                    },
                    {
                      name: "Business Investment",
                      onClick: (e) => {
                        setSortFilter("Business Investment");
                      },
                    },
                    {
                      name: "Business Loan",
                      onClick: (e) => {
                        setSortFilter("Business Loan");
                      },
                    },
                    {
                      name: "Asset for Sale",
                      onClick: (e) => {
                        setSortFilter("Asset for Sale");
                      },
                    },
                  ]}
                  title="Sort by:"
                  value={sortFilter}
                />
                <DropdownButton
                  menus={[
                    {
                      name: "Proposed",
                      onClick: (e) => {
                        setFilter("Proposed");
                      },
                    },
                    {
                      name: "Accepted",
                      onClick: (e) => {
                        setFilter("Accepted");
                      },
                    },
                    {
                      name: "Rejected",
                      onClick: (e) => {
                        setFilter("Rejected");
                      },
                    },
                  ]}
                  title="Filter by:"
                  value={filter}
                />
              </div>
            </div>

            <div className="md:px-5 md:flex md:flex-col mt-6">
              {businesses.map((business, i) => {
                return (
                  <BusinessCard
                    key={i}
                    business={business}
                    onClick={(e) => {}}
                  />
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

interface iBusinessCardData {
  business: iBusinessData;
  onClick: MouseEventHandler;
}

const BusinessCard: FC<iBusinessCardData> = ({ business, onClick }) => {
  return (
    <div className="px-4 md:px-0 cursor-pointer" onClick={onClick}>
      <div className="bg-input md:bg-white rounded">
        <div className="relative pt-4 mb-4 md:pt-0 md:pb-0">
          <div className="flex gap-4 md:flex-col md:gap-0">
            <div className="ml-4 md:ml-0 md:w-full md:relative">
              <Image
                src={business.image}
                alt={""}
                className="md:w-[100%] md:object-cover h-[90%] md:h-40 rounded-[10px] md:rounded-b-none"
              />
              <div
                className={`md:block hidden absolute top-0 right-0 ${
                  business.status === PROPOSED
                    ? "bg-role-orange-bg text-role-orange"
                    : business.status === ACCEPTED
                    ? "bg-role-green-bg text-role-green"
                    : "bg-role-red-bg text-error"
                } rounded-tr-[10px] px-3`}
              >
                {business.status}
              </div>
            </div>
            <div className="md:flex md:flex-col md:border-contrast-10 md:border-[1.5px] md:border-t-0 md:px-4 rounded-b-[10px] mb-4">
              <div className="flex w-full justify-between items-center pr-4 md:pr-0">
                <h2 className="bold-2 md:text-[16px] md:leading-[28px] mb-2 text-contrast-100 md:mt-2">
                  {business.name}
                </h2>

                <div className="flex gap-2 items-center">
                  <div
                    className={`p-[6px] rounded-full ${
                      business.liked ? "bg-role-red-bg" : "bg-contrast-10"
                    }`}
                  >
                    <FaHeart
                      size={"18px"}
                      fill={business.liked ? "#FF0000" : "#C2C2C2"}
                    />
                  </div>

                  <div
                    className={`${
                      business.status === PROPOSED
                        ? "bg-role-orange-bg text-role-orange"
                        : business.status === ACCEPTED
                        ? "bg-role-green-bg text-role-green"
                        : "bg-role-red-bg text-error"
                    } px-2 rounded-full py-1 med-3 md:hidden`}
                  >
                    {business.status}
                  </div>
                </div>
              </div>
              <p className="med-3 md:hidden text-contrast-base pr-4">
                {business.description}
              </p>
              <div
                className={`flex items-center gap-2 md:mb-4 mt-2 justify-between`}
              >
                <div className="flex items-center gap-1 md:flex-col w-fit md:w-full md:items-start">
                  <div className="flex items-center gap-1">
                    <div className="bg-contrast-20 rounded-full p-[6px] w-8 h-8 md:w-6 md:h-6 md:p-[2px]">
                      <LocationIcon />
                    </div>
                    <div className="font-bold text-contrast-70 med-3 md:text-[12px] md:leading-[16px]">
                      {business.location}
                    </div>
                  </div>
                  <div className="custom-separator md:hidden mx-1" />
                  <div className="flex items-center gap-1">
                    <div className="bg-contrast-20 rounded-full p-[6px] w-8 h-8 md:w-6 md:h-6 md:p-[2px]">
                      <LocationIcon />
                    </div>
                    <div className="font-bold text-contrast-70 med-3 md:text-[12px] md:leading-[16px]">
                      {business.interest}
                    </div>
                  </div>
                  <div className="custom-separator md:hidden mx-1" />
                  <div className="flex items-center gap-1">
                    <div className="bg-contrast-20 rounded-full p-[6px] w-8 h-8 md:w-6 md:h-6 md:p-[2px]">
                      <LocationIcon />
                    </div>
                    <div className="font-bold text-contrast-70 med-3 md:text-[12px] md:leading-[16px]">
                      {business.businessStatus}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2 pb-2 md:hidden pr-4">
                  <p className={`med-4 text-contrast-base md:hidden `}>
                    Amount:
                  </p>
                  <p
                    className={`font-normal text-[12px] leading-[24px] text-green-100 `}
                  >
                    NGN{" "}
                    <span className="font-bold text-[18px]">
                      {formatNumberWithCommas(business.amount)}
                    </span>
                  </p>
                </div>

                <p className="font-normal text-[12px] leading-[24px] text-green-100 md:block hidden w-full md:text-right">
                  NGN{" "}
                  <span className="font-bold text-[18px]">
                    {formatNumberWithCommas(business.amount)}
                  </span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BuyerOverview;

/**
 * <>
      <div className="pt-4 overflow-y-scroll h-[90vh] md:h-auto px-[40px] md:px-5 pb-10">
        <div
          className={`mb-6 overflow-hidden transition-all duration-500 ease-in-out ${
            collapse ? "max-h-0" : "max-h-[1000px]"
          }`}
        >
          <h2 className="text-3xl md:text-[20px] md:leading-[30px] font-bold text-black md:mt-10 mt-2">
            Overview
          </h2>
          <div className="flex justify-between md:gap-6 md:justify-start mt-4 md:overflow-x-auto scrollbar-custom">
            <DashboardCard
              leading={"Total Balance"}
              content={"₦400,000"}
              trailing={`${convertDateWithSlashes(new Date())} last withdrawn`}
              chart={Chart1}
              tooltip={
                "This shows the cumulative revenue generated by your company throughout its years of operation."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Total Sold Acquisitions"}
              content={"50"}
              trailing={"09 businesses"}
              chart={Chart2}
              tooltip={
                "This shows the total number of companies you have acquired."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Total Proposed Businesses"}
              content={"32"}
              trailing={"09 businesses"}
              chart={Chart3}
              tooltip={"This shows your company's total years of operation."}
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
          </div>
        </div>

        <div className="flex justify-between md:flex-col md:mb-10 w-full">
          <div className="bg-white rounded border-contrast-10 border-[1.5px] w-full shadow-sm">
            <div className="flex justify-between px-4 h-[74px] md:h-[70px] items-center border-b-[1.5px] border-contrast-10">
              <h2 className="bold-1 md:text-[20px] md:leading-[30px] text-contrast-100">
                Acquired Businesses
              </h2>

              <p
                onClick={() => {
                  shouldCollapse(!collapse);
                }}
                className="text-blue-base med-3 md:text-[14px] md:leading-[24px] cursor-pointer"
              >
                {collapse ? "View less" : "View all"}
              </p>
            </div>

            <div className="md:px-5 md:flex md:flex-col mt-6">
              {businesses.map((business, i) => {
                return <div id={"" + i}></div>;
              })}
            </div>
          </div>
        </div>
      </div>
    </>
 */
