"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import Auto from "@/public/assets/Rectangle 101.png";

import Chart1 from "@/public/assets/Chart 1.png";
import Chart2 from "@/public/assets/Chart 2.png";
import Chart3 from "@/public/assets/Chart 3.png";

import { useState, useEffect } from "react";
import DropdownButton from "../../../DropdownButton/DropdownButton";
import { iBusinessData, ACCEPTED, REJECTED, PROPOSED } from "./BusinessData";

import ViewBusiness from "./ViewBusiness";
import BusinessCard from "./BusinessCard";

function convertDateWithSlashes(date: Date) {
  return `${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`;
}

const BuyerOverview = () => {
  const [businesses, setBusinesses] = useState<iBusinessData[]>([]);
  const [sortFilter, setSortFilter] = useState<string | null>(null);
  const [filter, setFilter] = useState<string | null>(null);
  const [currentBusiness, setCurrentBusiness] = useState<number>(-1);

  useEffect(() => {
    setBusinesses([
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Business for sale",
        interest: "Agriculture Web",
        liked: true,
        status: PROPOSED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Investment required",
        interest: "Agriculture Web",
        liked: false,
        status: ACCEPTED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Loan required",
        interest: "Agriculture Web",
        liked: false,
        status: REJECTED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Business for sale",
        interest: "Agriculture Web",
        liked: true,
        status: PROPOSED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Investment required",
        interest: "Agriculture Web",
        liked: false,
        status: ACCEPTED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "Oyo State, Nigeria",
        businessStatus: "Loan required",
        interest: "Agriculture Web",
        liked: false,
        status: REJECTED,
      },
    ]);
  }, []);

  return (
    <>
      {currentBusiness === -1 ? (
        <div className="pt-4 overflow-y-scroll h-[90vh] md:h-auto px-6 md:px-5 pb-10">
          <h2 className="text-3xl md:text-[20px] md:leading-[30px] font-bold text-black md:mt-10 mt-2">
            Overview
          </h2>
          <div className="flex justify-between md:gap-6 md:justify-start mt-4 md:overflow-x-auto scrollbar-custom">
            <DashboardCard
              leading={"Total Balance"}
              content={"₦400,000"}
              trailing={`${convertDateWithSlashes(new Date())} last withdrawn`}
              chart={Chart1}
              tooltip={
                "This shows the cumulative revenue generated by your company throughout its years of operation."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Total Sold Acquisitions"}
              content={"50"}
              trailing={"09 businesses"}
              chart={Chart2}
              tooltip={
                "This shows the total number of companies you have acquired."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Total Proposed Businesses"}
              content={"32"}
              trailing={"09 businesses"}
              chart={Chart3}
              tooltip={"This shows your company's total years of operation."}
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
          </div>
          <div className="flex justify-between md:flex-col md:mb-10 w-full mt-6">
            <div className="bg-white rounded border-contrast-10 border-[1.5px] w-full shadow-sm">
              <div className="flex md:flex-col md:justify-center justify-between px-4 h-[74px] md:h-[122px] md:items-start items-center border-b-[1.5px] border-contrast-10">
                <h2 className="bold-1 md:text-[20px] md:leading-[30px] text-contrast-100">
                  Acquired Businesses
                </h2>

                <div className="flex gap-3 md:mt-4">
                  <DropdownButton
                    menus={[
                      {
                        name: "Business for Sale",
                        onClick: (e) => {
                          setSortFilter("Business for Sale");
                        },
                      },
                      {
                        name: "Business Investment",
                        onClick: (e) => {
                          setSortFilter("Business Investment");
                        },
                      },
                      {
                        name: "Business Loan",
                        onClick: (e) => {
                          setSortFilter("Business Loan");
                        },
                      },
                      {
                        name: "Asset for Sale",
                        onClick: (e) => {
                          setSortFilter("Asset for Sale");
                        },
                      },
                    ]}
                    title="Sort by:"
                    value={sortFilter}
                  />
                  <DropdownButton
                    menus={[
                      {
                        name: "Proposed",
                        onClick: (e) => {
                          setFilter("Proposed");
                        },
                      },
                      {
                        name: "Accepted",
                        onClick: (e) => {
                          setFilter("Accepted");
                        },
                      },
                      {
                        name: "Rejected",
                        onClick: (e) => {
                          setFilter("Rejected");
                        },
                      },
                    ]}
                    title="Filter by:"
                    value={filter}
                  />
                </div>
              </div>

              <div className="md:px-5 md:flex md:flex-col mt-6">
                {businesses.map((business, i) => {
                  return (
                    <BusinessCard
                      key={i}
                      business={business}
                      onClick={(e) => {
                        setCurrentBusiness(i);
                      }}
                    />
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      ) : (
        <ViewBusiness
          business={businesses[currentBusiness]}
          onExit={() => {
            setCurrentBusiness(-1);
          }}
        />
      )}
    </>
  );
};

export default BuyerOverview;

/**
 * <>
      <div className="pt-4 overflow-y-scroll h-[90vh] md:h-auto px-[40px] md:px-5 pb-10">
        <div
          className={`mb-6 overflow-hidden transition-all duration-500 ease-in-out ${
            collapse ? "max-h-0" : "max-h-[1000px]"
          }`}
        >
          <h2 className="text-3xl md:text-[20px] md:leading-[30px] font-bold text-black md:mt-10 mt-2">
            Overview
          </h2>
          <div className="flex justify-between md:gap-6 md:justify-start mt-4 md:overflow-x-auto scrollbar-custom">
            <DashboardCard
              leading={"Total Balance"}
              content={"₦400,000"}
              trailing={`${convertDateWithSlashes(new Date())} last withdrawn`}
              chart={Chart1}
              tooltip={
                "This shows the cumulative revenue generated by your company throughout its years of operation."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Total Sold Acquisitions"}
              content={"50"}
              trailing={"09 businesses"}
              chart={Chart2}
              tooltip={
                "This shows the total number of companies you have acquired."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Total Proposed Businesses"}
              content={"32"}
              trailing={"09 businesses"}
              chart={Chart3}
              tooltip={"This shows your company's total years of operation."}
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
          </div>
        </div>

        <div className="flex justify-between md:flex-col md:mb-10 w-full">
          <div className="bg-white rounded border-contrast-10 border-[1.5px] w-full shadow-sm">
            <div className="flex justify-between px-4 h-[74px] md:h-[70px] items-center border-b-[1.5px] border-contrast-10">
              <h2 className="bold-1 md:text-[20px] md:leading-[30px] text-contrast-100">
                Acquired Businesses
              </h2>

              <p
                onClick={() => {
                  shouldCollapse(!collapse);
                }}
                className="text-blue-base med-3 md:text-[14px] md:leading-[24px] cursor-pointer"
              >
                {collapse ? "View less" : "View all"}
              </p>
            </div>

            <div className="md:px-5 md:flex md:flex-col mt-6">
              {businesses.map((business, i) => {
                return <div id={"" + i}></div>;
              })}
            </div>
          </div>
        </div>
      </div>
    </>
 */
