"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import ShopDrafts from "@/public/components/Drafts/ShopDrafts";

import { iDraft } from "@/public/components/Drafts/DraftCard";
import Auto from "@/public/assets/Rectangle 101.png";

import Button from "@/public/components/Button";
import { IoIosArrowForward, IoIosArrowBack } from "react-icons/io";
import { FC, useEffect, useState } from "react";

import { Switch } from "@mantine/core";

interface iViewDraft {
  draft: iDraft;
  onExit: any;
}

const Store = () => {
  const [currentDraft, setCurrentDraft] = useState<number>(-1);
  const [businessData, setBusinessData] = useState<number[]>([]);

  const drafts: iDraft[] = [
    {
      image: Auto,
      price: 400000,
      likes: 0,
      clicks: 0,
      requests: 0,
      active: false,
      description:
        "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
      title: "Auto Component Distribution Company",
    },
    {
      image: Auto,
      price: 400000,
      likes: 0,
      clicks: 0,
      requests: 0,
      active: true,
      description:
        "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
      title: "Auto Component Distribution Company",
    },
    {
      image: Auto,
      price: 400000,
      likes: 0,
      clicks: 0,
      requests: 0,
      active: true,
      description:
        "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
      title: "Auto Component Distribution Company",
    },
    {
      image: Auto,
      price: 400000,
      likes: 0,
      clicks: 0,
      requests: 0,
      active: true,
      description:
        "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
      title: "Auto Component Distribution Company",
    },
  ];

  function getBusinessesData() {
    let activeBusiness = 0,
      archivedBusiness = 0;
    if (drafts.length > 0) {
      for (let i = 0; i < drafts.length; ++i) {
        if (drafts[i].active) {
          ++activeBusiness;
        } else {
          ++archivedBusiness;
        }
      }
    }

    return [activeBusiness, archivedBusiness];
  }

  useEffect(() => {
    let totalBusiness = drafts.length;
    const [active, archived] = getBusinessesData();
    setBusinessData([totalBusiness, active, archived]);
  }, []);

  return (
    <>
      <div className="px-6 pt-4 overflow-y-scroll h-[90vh] md:h-auto pb-10">
        {currentDraft === -1 ? (
          <>
            <h2 className="text-3xl md:text-[20px] md:leading-[30px] font-bold text-black md:mt-10 mt-2">
              Store
            </h2>
            <div className="flex justify-between md:gap-6 md:justify-start mt-4 md:overflow-x-auto scrollbar-custom">
              <DashboardCard
                leading={"Total Businesses"}
                content={"" + businessData[0]}
                trailing={"09 business"}
                tooltip={"This shows the cumulative revenue generated by your company throughout its years of operation."}
                className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]" chart={undefined}              />
              <DashboardCard
                leading={"Active Businesses"}
                content={"" + businessData[1]}
                trailing={"09 businesses"}
                className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
                tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}              />
              <DashboardCard
                leading={"Archived Businesses"}
                content={"" + businessData[2]}
                trailing={"31/04/2023"}
                className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
                tooltip={"This shows your company's total years of operation"} chart={undefined}              />
            </div>

            <div className="pt-4">
              <ShopDrafts
                drafts={drafts}
                onSelectDraft={(index: number) => {
                  setCurrentDraft(index);
                }}
              />
            </div>
          </>
        ) : (
          <ViewDraft
            draft={drafts[currentDraft]}
            onExit={() => {
              setCurrentDraft(-1);
            }}
          />
        )}
      </div>
    </>
  );
};

const ViewDraft: FC<iViewDraft> = ({ draft, onExit }) => {
  return (
    <div className="flex flex-col w-full">
      <div className="flex justify-between items-center w-full">
        <div className="flex gap-2 bold-2 items-center">
          <div onClick={onExit} className="cursor-pointer">
            <IoIosArrowBack fill="#141414" />
          </div>
          {draft.title}
        </div>
        <div className="flex gap-4 items-center med-3 md:hidden">
          <Switch
            value={"" + draft.active}
            label={"Activated"}
            width={"25px"}
          />
          <Button
            type="button"
            height="h-[40px]"
            width={`md:w-[30vw] w-auto`}
            className={`rounded-[5px] px-3 flex justify-center items-center gap-1 text-white`}
            colorType="primary"
            handleClick={() => {}}
          >
            Edit
          </Button>
        </div>
      </div>
      <div className="flex justify-between md:gap-6 md:justify-start mt-6 md:overflow-x-auto scrollbar-custom">
        <DashboardCard
          leading={"Full Sale"}
          content={draft.price.toLocaleString("en-US")}
          trailing={"Lagos, Nigeria"}
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]" chart={undefined}        />
        <DashboardCard
          leading={"Reported Sales"}
          content={"400,000"}
          trailing={"Yearly records"}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}        />
        <DashboardCard
          leading={"Years of existence"}
          content={"12 - 15"}
          trailing={"15-20 employees"}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}        />

        <DashboardCard
          leading={"Requests"}
          content={"" + draft.requests}
          trailing={""}
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px] hidden md:block" chart={undefined}        />
        <DashboardCard
          leading={"Clicks"}
          content={"" + draft.clicks}
          trailing={""}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px] hidden md:block"
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}        />
        <DashboardCard
          leading={"Likes"}
          content={"" + draft.likes}
          trailing={""}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px] hidden md:block"
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}        />
      </div>
      <div className="flex justify-between md:gap-6 md:justify-start mt-6 md:hidden">
        <DashboardCard
          leading={"Requests"}
          content={"" + draft.requests}
          trailing={""}
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]" chart={undefined}        />
        <DashboardCard
          leading={"Clicks"}
          content={"" + draft.clicks}
          trailing={""}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}        />
        <DashboardCard
          leading={"Likes"}
          content={"" + draft.likes}
          trailing={""}
          className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
          tooltip={"Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."} chart={undefined}        />
      </div>
    </div>
  );
};

export default Store;
