"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import AcquiredBusinessCard from "@/public/components/AcquiredBusinessCard/AcquiredBusinessCard";

const Overview = () => {
  return (
    <>
      <div className="px-6 pt-4 overflow-y-scroll h-[85vh]">
        <h2 className="text-2xl font-bold text-black">Overview</h2>
        <div className="flex justify-between pt-4">
          <DashboardCard
            heading={"Total Sold Businesses"}
            amount={"₦400,000"}
            date={"31/04/2023 last top-up"}
            info={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
          />
          <DashboardCard
            heading={"Total Acquisitions"}
            amount={"50"}
            date={"09 businesses"}
            info={
              "Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."
            }
          />
          <DashboardCard
            heading={"Total Proposed Businesses"}
            amount={"32"}
            date={"02 businesses"}
            info={
              "This shows your company's total years of operation"
            }
          />
        </div>

        <div className="pt-4">
            <AcquiredBusinessCard />
        </div>
      </div>
    </>
  );
};

export default Overview;
