"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import AcquiredBusinessCard from "@/public/components/AcquiredBusinessCard/AcquiredBusinessCard";

const Overview = () => {
  return (
    <>
      <div className="px-6 pt-4 overflow-y-scroll h-[85vh]">
        <h2 className="text-2xl font-bold text-black">Overview</h2>
        <div className="flex justify-between pt-4">
          <DashboardCard
            leading={"Total Sold Businesses"}
            content={"₦400,000"}
            trailing={"31/04/2023 last top-up"}
            tooltip={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
          />
          <DashboardCard
            leading={"Total Acquisitions"}
            content={"50"}
            trailing={"09 businesses"}
            tooltip={
              "Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."
            }
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
          />
          <DashboardCard
            leading={"Total Proposed Businesses"}
            content={"32"}
            trailing={"02 businesses"}
            tooltip={"This shows your company's total years of operation"}
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
          />
        </div>

        <div className="pt-4">
          <AcquiredBusinessCard />
        </div>
      </div>
    </>
  );
};

export default Overview;
