"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import Auto from "@/public/assets/Rectangle 101.png";

import Chart1 from "@/public/assets/Chart 1.png";
import Chart2 from "@/public/assets/Chart 2.png";
import Chart3 from "@/public/assets/Chart 3.png";

import { useState, useEffect } from "react";
import DropdownButton from "../../../DropdownButton/DropdownButton";
import { iStoreData, ACTIVE, ARCHIVED } from "./StoreData";

import StoreCard from "./StoreCard";
import ViewStore from "./ViewStore";

function convertDateWithSlashes(date: Date) {
  return `${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`;
}

const StorePage = () => {
  const [stores, setStores] = useState<iStoreData[]>([]);
  const [sortFilter, setSortFilter] = useState<string | null>(null);
  const [filter, setFilter] = useState<string | null>(null);
  const [currentStore, setCurrentStore] = useState<number>(-1);

  useEffect(() => {
    setStores([
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "0 Requests",
        storeStatus: "0 Clicks",
        interest: "0 Likes",
        liked: true,
        status: ACTIVE,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "20 Requests",
        storeStatus: "30,730 Clicks",
        interest: "100 Likes",
        liked: false,
        status: ARCHIVED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "200 Requests",
        storeStatus: "50,730 Clicks",
        interest: "1000 Likes",
        liked: true,
        status: ACTIVE,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "2 Requests",
        storeStatus: "30 Clicks",
        interest: "10 Likes",
        liked: false,
        status: ARCHIVED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "50 Requests",
        storeStatus: "50,730 Clicks",
        interest: "500 Likes",
        liked: false,
        status: ARCHIVED,
      },
      {
        image: Auto,
        name: "Auto Repair and Service Opportunity",
        description:
          "Paggico is a growing car wash that caters to the every need of your autombiles. Paggico is a growing car wash that caters to the every need of your autombiles",
        amount: 400000,
        location: "10 Requests",
        storeStatus: "10,730 Clicks",
        interest: "10 Likes",
        liked: true,
        status: ACTIVE,
      },
    ]);
  }, []);

  return (
    <>
      {currentStore === -1 ? (
        <div className="pt-4 overflow-y-scroll h-[90vh] md:h-auto px-6 md:px-5 pb-10">
          <h2 className="text-3xl md:text-[20px] md:leading-[30px] font-bold text-black md:mt-10 mt-2">
            Store
          </h2>
          <div className="flex justify-between md:gap-6 md:justify-start mt-4 md:overflow-x-auto scrollbar-custom">
            <DashboardCard
              leading={"Total Businesses"}
              content={"23"}
              trailing={"09 businesses"}
              chart={Chart1}
              tooltip={
                "This shows the cumulative revenue generated by your company throughout its years of operation."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Active Businesses"}
              content={"03"}
              trailing={"09 businesses"}
              chart={Chart2}
              tooltip={
                "This shows the total number of companies you have acquired."
              }
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
            <DashboardCard
              leading={"Archived Businesses"}
              content={"02"}
              trailing={`${convertDateWithSlashes(new Date())} last withdrawn`}
              chart={Chart3}
              tooltip={"This shows your company's total years of operation."}
              className="w-[32%] md:w-[320px] bg-white rounded border-contrast-10 border-[1.5px]"
            />
          </div>
          <div className="flex justify-between md:flex-col md:mb-10 w-full mt-6">
            <div className="bg-white rounded border-contrast-10 border-[1.5px] w-full shadow-sm">
              <div className="flex md:flex-col md:justify-center justify-between px-4 h-[74px] md:h-[122px] md:items-start items-center border-b-[1.5px] border-contrast-10">
                <h2 className="bold-1 md:text-[20px] md:leading-[30px] text-contrast-100">
                  Draft
                </h2>

                <div className="flex gap-3 md:mt-4">
                  <DropdownButton
                    menus={[
                      {
                        name: "Business for Sale",
                        onClick: (e) => {
                          setSortFilter("Business for Sale");
                        },
                      },
                      {
                        name: "Business Investment",
                        onClick: (e) => {
                          setSortFilter("Business Investment");
                        },
                      },
                      {
                        name: "Business Loan",
                        onClick: (e) => {
                          setSortFilter("Business Loan");
                        },
                      },
                      {
                        name: "Asset for Sale",
                        onClick: (e) => {
                          setSortFilter("Asset for Sale");
                        },
                      },
                    ]}
                    title="Sort by:"
                    value={sortFilter}
                  />
                  <DropdownButton
                    menus={[
                      {
                        name: "Proposed",
                        onClick: (e) => {
                          setFilter("Proposed");
                        },
                      },
                      {
                        name: "Accepted",
                        onClick: (e) => {
                          setFilter("Accepted");
                        },
                      },
                      {
                        name: "Rejected",
                        onClick: (e) => {
                          setFilter("Rejected");
                        },
                      },
                    ]}
                    title="Filter by:"
                    value={filter}
                  />
                </div>
              </div>

              <div className="md:px-5 md:flex md:flex-col mt-6">
                {stores.map((store, i) => {
                  return (
                    <StoreCard
                      key={i}
                      store={store}
                      onClick={(e) => {
                        setCurrentStore(i);
                      }}
                    />
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      ) : (
        <ViewStore
          store={stores[currentStore]}
          onExit={() => {
            setCurrentStore(-1);
          }}
        />
      )}
    </>
  );
};

export default StorePage;