"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import DraftsCard from "@/public/components/DraftsCard/DraftsCard";

const Store = () => {
  return (
    <>
      <div className="px-6 pt-4 overflow-y-scroll h-[85vh]">
        <h2 className="text-2xl font-bold text-black">Store</h2>
        <div className="flex justify-between pt-4">
          <DashboardCard
            heading={"Total Businesses"}
            amount={"23"}
            date={"09 business"}
            info={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
          />
          <DashboardCard
            heading={"Active Businesses"}
            amount={"03"}
            date={"09 businesses"}
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
            info={
              "Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."
            }
          />
          <DashboardCard
            heading={"Archived Businesses"}
            amount={"02"}
            date={"31/04/2023"}
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
            info={"This shows your company's total years of operation"}
          />
        </div>

        <div className="pt-4">
          <DraftsCard />
        </div>
      </div>
    </>
  );
};

export default Store;
