"use client";
import DashboardCard from "@/public/components/DashboardCard/DashboardCard";
import ShopDrafts from "@/public/components/Drafts/ShopDrafts";

const Store = () => {
  return (
    <>
      <div className="px-6 pt-4 overflow-y-scroll h-[85vh]">
        <h2 className="text-2xl font-bold text-black">Store</h2>
        <div className="flex justify-between pt-4">
          <DashboardCard
            leading={"Total Businesses"}
            content={"23"}
            trailing={"09 business"}
            tooltip={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
          />
          <DashboardCard
            leading={"Active Businesses"}
            content={"03"}
            trailing={"09 businesses"}
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
            tooltip={
              "Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."
            }
          />
          <DashboardCard
            leading={"Archived Businesses"}
            content={"02"}
            trailing={"31/04/2023"}
            className="w-80 md:w-72 bg-white rounded border-border-black border-[1.5px]"
            tooltip={"This shows your company's total years of operation"}
          />
        </div>

        <div className="pt-4">
          <ShopDrafts />
        </div>
      </div>
    </>
  );
};

export default Store;
