"use client";
import StoreCard from "@/public/components/StoreCard/StoreCard";
import { ArrowLeftIcon } from "@/public/icons/arrow-left-icon";
import { TbPencil } from "react-icons/tb";
import * as Tabs from "@radix-ui/react-tabs";
import BusinessOverview from "@/public/components/BusinessOverview/BusinessOverview";
import RequestCardIcon from "@/public/components/RequestCardIcon/RequestCardIcon";
import Attachments from "@/public/components/Attachments/Attachments";
import BusinessGallery from "@/public/components/BusinessGallery/BusinessGallery";

const ExpandableStore = () => {
  return (
    <>
      <div className="px-6 pt-4 overflow-y-scroll h-[85vh]">
        <div className="flex items-center justify-between pb-4">
          <div className="flex items-center">
            <ArrowLeftIcon />
            <h2 className="font-bold text-[20px] leading-[30px] text-light-black-6">
              Auto Repair and Service Opportunity
            </h2>
          </div>

          <div className="">
            <button className="w-[87px] h-[40px] rounded-lg flex gap- items-center justify-center text-white bg-light-blue text-base font-medium ">
              <TbPencil />
              Edit
            </button>
          </div>
        </div>

        <div className="flex justify-between">
          <StoreCard
            heading={"Full Sale"}
            amount={"₦400,000"}
            date={"Lagos, Nigeria."}
            info={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
          />
          <StoreCard
            heading={"Reported Sales"}
            amount={"₦400,000"}
            date={"Yearly records"}
            info={
              "Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."
            }
          />
          <StoreCard
            heading={"Years of Existence"}
            amount={"₦400,000"}
            date={"15 - 20 employees "}
            info={"This shows your company's total years of operation"}
          />
        </div>

        <div className="flex justify-between pt-4">
          <StoreCard
            heading={"Requests"}
            amount={"20"}
            date={""}
            info={
              "This shows the cumulative revenue generated by your company throughout its years of operation."
            }
          />
          <StoreCard
            heading={"Clicks"}
            amount={"30,730"}
            date={""}
            info={
              "Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit. Lorem ipsum dolor sit amet, cons  piscing elit lorem ipsumsit..."
            }
          />
          <StoreCard
            heading={"Likes"}
            amount={"100"}
            date={""}
            info={"This shows your company's total years of operation"}
          />
        </div>

        <div className="flex justify-between pt-4 pb-16">
          <div className="chart-width">
            <div className="pb-4">
              <div className="w-full bg-white rounded">

                <Tabs.Root className=" " defaultValue="tab1">
                  <Tabs.List
                    className="shrink-0 flex gap-8 border-b-[1px] border-light-black-1"
                    aria-label="Manage your account"
                  >
                    <Tabs.Trigger
                      className="bg-white text-light-black-4 px-4 h-[45px] flex items-center text-base font-medium select-none first:rounded-tl-md  last:rounded-tr-md data-[state=active]:text-green data-[state=active]:shadow-[inset_0_-1px_0_0,0_1px_0_0] data-[state=active]:shadow-current data-[state=active]:focus:relative outline-none cursor-default"
                      value="tab1"
                    >
                     Business Overview
                    </Tabs.Trigger>
                    <Tabs.Trigger
                      className="bg-white text-light-black-4 px-4 h-[45px] flex items-center text-base font-medium select-none first:rounded-tl-md  last:rounded-tr-md data-[state=active]:text-green data-[state=active]:shadow-[inset_0_-1px_0_0,0_1px_0_0] data-[state=active]:shadow-current data-[state=active]:focus:relative outline-none cursor-default"
                      value="tab2"
                    >
                      Attachments
                    </Tabs.Trigger>
                    <Tabs.Trigger
                      className="bg-white text-light-black-4 px-4 h-[45px] flex items-center text-base font-medium select-none first:rounded-tl-md  last:rounded-tr-md data-[state=active]:text-green data-[state=active]:shadow-[inset_0_-1px_0_0,0_1px_0_0] data-[state=active]:shadow-current data-[state=active]:focus:relative outline-none cursor-default"
                      value="tab3"
                    >
                     Business Gallery
                    </Tabs.Trigger>
                  </Tabs.List>
                  <Tabs.Content
                    className="grow pt-8 bg-white rounded"
                    value="tab1"
                  >
                    <BusinessOverview />
                  </Tabs.Content>
                  <Tabs.Content
                    className="grow pt-8 bg-white rounded"
                    value="tab2"
                  >
                    <Attachments />
                  </Tabs.Content>
                  <Tabs.Content
                    className="grow pt-8 bg-white rounded"
                    value="tab3"
                  >
                    <BusinessGallery />
                  </Tabs.Content>
                </Tabs.Root>
              </div>
            </div>
          </div>

          <div>
            <RequestCardIcon />
          </div>
        </div>
      </div>
    </>
  );
};

export default ExpandableStore;
